from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',
		views.home_page,
		name='home_page'),
	url(r'^anatomy/$',
		views.anatomy,
		name='anatomy'),
	url(r'^chemistry/$',
		views.chemistry,
		name='chemistry'),
	url(r'^anatomy/(?P<pk>\d+)/$',
		views.anatomy_detail,
		name='anatomy_detail'),
	url(r'^chemistry/(?P<cm>\d+)/$',
		views.chemistry_detail,
		name='chemistry_detail'),
	url(r'^languages/$',
		views.languages,
		name='languages'),
	url(r'^languages/english/$',
		views.english,
		name='english'),
	url(r'^languages/english/(?P<eng>\d+)/$',
		views.english_detail,
		name='english_detail'),
	url(r'^languages/german/$',
		views.german,
		name='german'),
	url(r'^languages/russian/$',
		views.russian,
		name='russian'),
	url(r'^anatomy/new/$',
		views.anatomy_new,
		name='anatomy_new'),
	url(r'^chemistry/new/$',
		views.chemistry_new,
		name='chemistry_new'),
	url(r'^languages/german/(?P<gm>\d+)/$',
		views.german_detail,
		name='german_detail'),
	url(r'^languages/german/new/$',
		views.german_new,
		name='german_new'),
	url(r'^languages/russian/(?P<rn>\d+)/$',
		views.russian_detail,
		name='russian_detail'),
	url(r'^languages/russian/new/$',
		views.russian_new,
		name='russian_new'),
	url(r'^languages/english/new/$',
		views.english_new,
		name='english_new'),


]
